### ISSUE TITLE
你这代码有问题啊

### ISSUE THREAD

**Issue by KimoriTama** [cznull/pcrgames#1]
我环境配了一天了最后还运行不了
![屏幕截图(35)](https://user-images.githubusercontent.com/64054139/129378081-db3bedb7-66b8-46f4-ac34-f8f81ce72ab3.png)

**Comment by myjdem** [comment]
你搞错了不需要编译的，还有其他文件的有exe，去主页看简介https://github.com/cznull/pcrgames

**Comment by KimoriTama** [comment]
> 你搞错了不需要编译的，还有其他文件的有exe，去主页看简介https://github.com/cznull/pcrgames

你看错了，都不是一个项目，我说的是香织的灵魂空手道的项目。
